import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerDesignReview } from "./tools/design-review.js";
import { registerDesignFix } from "./tools/design-fix.js";
import { registerColorPalette } from "./tools/color-palette.js";
import { registerComponentSuggest } from "./tools/component-suggest.js";
import { registerScanProject } from "./tools/scan-project.js";
import { registerDesignGuide } from "./tools/design-guide.js";
import { registerDesignReference } from "./tools/design-reference.js";
import { registerDesignIdentity } from "./tools/design-identity.js";
import { registerRenderAndReview } from "./tools/render-and-review.js";
import { registerScreenshotReview } from "./tools/screenshot-review.js";
import { registerDesignSession } from "./tools/design-session.js";
import { registerGeneratePage } from "./tools/generate-page.js";
import { registerDesignIterate } from "./tools/design-iterate.js";
import { registerFigmaTools } from "./tools/figma.js";
import { registerA11yAudit } from "./tools/a11y-audit.js";
import { registerAnalyzeUrl } from "./tools/analyze-url.js";
import { registerBatchAnalyze } from "./tools/batch-analyze.js";
import { registerDesignTrends } from "./tools/design-trends.js";
import { registerScreenshotToCode } from "./tools/screenshot-to-code.js";
import { registerScaffoldProject } from "./tools/scaffold-project.js";
import { registerLivePreview } from "./tools/live-preview.js";
import { registerResponsivePreview } from "./tools/responsive-preview.js";
import { registerExportTokens } from "./tools/export-tokens.js";
import { registerDesignCompare } from "./tools/design-compare.js";
import { registerBatchReview } from "./tools/batch-review.js";
import { registerSuggestAnimations } from "./tools/suggest-animations.js";
import { registerGenerateStyleGuide } from "./tools/generate-style-guide.js";
import { registerDesignWizard } from "./tools/design-wizard.js";
import { registerCompeteAnalyze } from "./tools/compete-analyze.js";
import { registerPerfAudit } from "./tools/perf-audit.js";
import { registerMigrateStyles } from "./tools/migrate-styles.js";
import { registerReferenceCompare } from "./tools/reference-compare.js";
import { registerDesignTransform } from "./tools/design-transform.js";
import { registerDesignRecipe } from "./tools/design-recipe.js";
import { registerDesignSystemResources } from "./resources/design-systems.js";

export function registerAllTools(server: McpServer): void {
  registerDesignReview(server);
  registerDesignFix(server);
  registerColorPalette(server);
  registerComponentSuggest(server);
  registerScanProject(server);
  registerDesignGuide(server);
  registerDesignReference(server);
  registerDesignIdentity(server);
  registerRenderAndReview(server);
  registerScreenshotReview(server);
  registerDesignSession(server);
  registerGeneratePage(server);
  registerDesignIterate(server);
  registerFigmaTools(server);
  registerA11yAudit(server);
  registerAnalyzeUrl(server);
  registerBatchAnalyze(server);
  registerDesignTrends(server);
  registerScreenshotToCode(server);
  registerScaffoldProject(server);
  registerLivePreview(server);
  registerResponsivePreview(server);
  registerExportTokens(server);
  registerDesignCompare(server);
  registerBatchReview(server);
  registerSuggestAnimations(server);
  registerGenerateStyleGuide(server);
  registerDesignWizard(server);
  registerCompeteAnalyze(server);
  registerPerfAudit(server);
  registerMigrateStyles(server);
  registerReferenceCompare(server);
  registerDesignTransform(server);
  registerDesignRecipe(server);
  registerDesignSystemResources(server);
}
