import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { loadContext, type DesignIdentityData } from "../context/project-context.js";
import {
  PERSONALITIES,
  generateIdentityPalette,
  getTypographySystem,
  getSpacingSystem,
  getCornerRadius,
  getShadowSystem,
  moodToHue,
} from "./design-identity.js";

// --- Token format generators ---

type TokenSet = {
  palette: Record<string, string>;
  typography: Record<string, string>;
  spacing: Record<string, string>;
  corners: Record<string, string>;
  shadows: Record<string, string>;
};

function identityToTokenSet(identity: DesignIdentityData): TokenSet {
  return {
    palette: identity.palette,
    typography: identity.typography,
    spacing: identity.spacing,
    corners: identity.corners,
    shadows: identity.shadows,
  };
}

function personalityToTokenSet(personalityName: string): TokenSet {
  const personality = PERSONALITIES.find(
    (p) => p.name.toLowerCase() === personalityName.toLowerCase()
  );
  if (!personality) {
    throw new Error(
      `Unknown personality "${personalityName}". Available: ${PERSONALITIES.map((p) => p.name).join(", ")}`
    );
  }

  const baseHue = moodToHue(personality.keywords[0] || "professional");
  const palette = generateIdentityPalette(personality, baseHue);
  const typography = getTypographySystem(personality.typographyVoice);
  const spacing = getSpacingSystem(personality.contentDensity);
  const corners = getCornerRadius(personality.cornerStyle);
  const shadows = getShadowSystem(personality.shadowStyle);

  return { palette, typography, spacing, corners, shadows };
}

// --- CSS Variables ---

function generateCSS(tokens: TokenSet): string {
  const lines = [":root {", "  /* Colors */"];
  for (const [key, value] of Object.entries(tokens.palette)) {
    lines.push(`  --color-${key.replace(/_/g, "-")}: ${value};`);
  }

  lines.push("", "  /* Typography */");
  for (const [key, value] of Object.entries(tokens.typography)) {
    lines.push(`  --${key.replace(/_/g, "-")}: ${value};`);
  }

  lines.push("", "  /* Spacing */");
  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`  --space-${key.replace(/_/g, "-")}: ${value};`);
  }

  lines.push("", "  /* Border Radius */");
  for (const [key, value] of Object.entries(tokens.corners)) {
    lines.push(`  --radius-${key}: ${value};`);
  }

  lines.push("", "  /* Shadows */");
  for (const [key, value] of Object.entries(tokens.shadows)) {
    lines.push(`  --shadow-${key}: ${value};`);
  }

  lines.push("}");
  return lines.join("\n");
}

// --- SCSS Variables ---

function generateSCSS(tokens: TokenSet): string {
  const lines = ["// Design Tokens (generated by devsigner)", "// Colors"];
  for (const [key, value] of Object.entries(tokens.palette)) {
    lines.push(`$color-${key.replace(/_/g, "-")}: ${value};`);
  }

  lines.push("", "// Typography");
  for (const [key, value] of Object.entries(tokens.typography)) {
    lines.push(`$${key.replace(/_/g, "-")}: ${value};`);
  }

  lines.push("", "// Spacing");
  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`$space-${key.replace(/_/g, "-")}: ${value};`);
  }

  lines.push("", "// Border Radius");
  for (const [key, value] of Object.entries(tokens.corners)) {
    lines.push(`$radius-${key}: ${value};`);
  }

  lines.push("", "// Shadows");
  for (const [key, value] of Object.entries(tokens.shadows)) {
    lines.push(`$shadow-${key}: ${value};`);
  }

  return lines.join("\n");
}

// --- Tailwind Config ---

function generateTailwind(tokens: TokenSet): string {
  // Build color object with shade scales
  const colors: Record<string, string | Record<string, string>> = {};
  for (const [key, value] of Object.entries(tokens.palette)) {
    const name = key.replace(/_/g, "-");
    // Primary and accent get a shade object; others stay flat
    if (key === "primary" || key === "accent") {
      colors[name] = {
        DEFAULT: value,
        50: adjustLightness(value, 0.95),
        100: adjustLightness(value, 0.9),
        200: adjustLightness(value, 0.8),
        300: adjustLightness(value, 0.7),
        400: adjustLightness(value, 0.6),
        500: value,
        600: adjustLightness(value, 0.4),
        700: adjustLightness(value, 0.3),
        800: adjustLightness(value, 0.2),
        900: adjustLightness(value, 0.1),
      };
    } else {
      colors[name] = value;
    }
  }

  // Build spacing
  const spacing: Record<string, string> = {};
  for (const [key, value] of Object.entries(tokens.spacing)) {
    spacing[key.replace(/_/g, "-")] = value;
  }

  // Build border radius
  const borderRadius: Record<string, string> = {};
  for (const [key, value] of Object.entries(tokens.corners)) {
    borderRadius[key] = value;
  }

  // Build box shadow
  const boxShadow: Record<string, string> = {};
  for (const [key, value] of Object.entries(tokens.shadows)) {
    boxShadow[key] = value;
  }

  // Build font family
  const fontFamily: Record<string, string[]> = {};
  if (tokens.typography.font_heading) {
    fontFamily.heading = tokens.typography.font_heading.split(",").map((f) => f.trim());
  }
  if (tokens.typography.font_body) {
    fontFamily.body = tokens.typography.font_body.split(",").map((f) => f.trim());
  }

  // Build font size
  const fontSize: Record<string, string> = {};
  const sizeKeys: Record<string, string> = {
    heading_xxl: "xxl",
    heading_xl: "xl",
    heading_lg: "lg",
    heading_md: "md",
    body_lg: "body-lg",
    body_md: "body",
    body_sm: "body-sm",
    caption: "caption",
  };
  for (const [key, alias] of Object.entries(sizeKeys)) {
    if (tokens.typography[key]) {
      fontSize[alias] = tokens.typography[key];
    }
  }

  const config = {
    theme: {
      extend: {
        colors,
        spacing,
        borderRadius,
        boxShadow,
        fontFamily,
        fontSize,
      },
    },
  };

  return `/** @type {import('tailwindcss').Config} */
module.exports = ${JSON.stringify(config, null, 2)};
`;
}

// --- W3C Design Tokens (JSON) ---

function generateJSON(tokens: TokenSet): string {
  const dtcg: Record<string, unknown> = {
    $schema: "https://design-tokens.github.io/community-group/format/",
    color: {} as Record<string, unknown>,
    typography: {} as Record<string, unknown>,
    spacing: {} as Record<string, unknown>,
    borderRadius: {} as Record<string, unknown>,
    shadow: {} as Record<string, unknown>,
  };

  const colorGroup = dtcg.color as Record<string, unknown>;
  for (const [key, value] of Object.entries(tokens.palette)) {
    colorGroup[key] = { $type: "color", $value: value };
  }

  const typoGroup = dtcg.typography as Record<string, unknown>;
  for (const [key, value] of Object.entries(tokens.typography)) {
    // Font families are "fontFamily" type, sizes are "dimension", weights are "number"
    if (key.startsWith("font_")) {
      typoGroup[key] = { $type: "fontFamily", $value: value };
    } else if (key.startsWith("weight_")) {
      typoGroup[key] = { $type: "number", $value: parseInt(value, 10) };
    } else if (key.startsWith("line_height_")) {
      typoGroup[key] = { $type: "number", $value: parseFloat(value) };
    } else if (key.startsWith("letter_spacing_")) {
      typoGroup[key] = { $type: "dimension", $value: value };
    } else {
      typoGroup[key] = { $type: "dimension", $value: value };
    }
  }

  const spacingGroup = dtcg.spacing as Record<string, unknown>;
  for (const [key, value] of Object.entries(tokens.spacing)) {
    spacingGroup[key] = { $type: "dimension", $value: value };
  }

  const radiusGroup = dtcg.borderRadius as Record<string, unknown>;
  for (const [key, value] of Object.entries(tokens.corners)) {
    radiusGroup[key] = { $type: "dimension", $value: value };
  }

  const shadowGroup = dtcg.shadow as Record<string, unknown>;
  for (const [key, value] of Object.entries(tokens.shadows)) {
    shadowGroup[key] = { $type: "shadow", $value: value };
  }

  return JSON.stringify(dtcg, null, 2);
}

// --- Figma Tokens ---

function generateFigmaTokens(tokens: TokenSet): string {
  const figma: Record<string, unknown> = {
    global: {
      color: {} as Record<string, unknown>,
      typography: {} as Record<string, unknown>,
      spacing: {} as Record<string, unknown>,
      borderRadius: {} as Record<string, unknown>,
      boxShadow: {} as Record<string, unknown>,
    },
    $themes: [],
    $metadata: {
      tokenSetOrder: ["global"],
    },
  };

  const global = figma.global as Record<string, Record<string, unknown>>;

  for (const [key, value] of Object.entries(tokens.palette)) {
    global.color[key] = { value, type: "color" };
  }

  for (const [key, value] of Object.entries(tokens.typography)) {
    if (key.startsWith("font_")) {
      global.typography[key] = { value, type: "fontFamilies" };
    } else if (key.startsWith("weight_")) {
      global.typography[key] = { value, type: "fontWeights" };
    } else if (key.startsWith("line_height_")) {
      global.typography[key] = { value, type: "lineHeights" };
    } else if (key.startsWith("letter_spacing_")) {
      global.typography[key] = { value, type: "letterSpacing" };
    } else {
      global.typography[key] = { value, type: "fontSizes" };
    }
  }

  for (const [key, value] of Object.entries(tokens.spacing)) {
    global.spacing[key] = { value, type: "spacing" };
  }

  for (const [key, value] of Object.entries(tokens.corners)) {
    global.borderRadius[key] = { value, type: "borderRadius" };
  }

  for (const [key, value] of Object.entries(tokens.shadows)) {
    global.boxShadow[key] = { value, type: "boxShadow" };
  }

  return JSON.stringify(figma, null, 2);
}

// --- Helper: adjust lightness of a hex color ---

function adjustLightness(hex: string, targetL: number): string {
  // Simple hex -> rgb -> hsl -> adjust -> rgb -> hex
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }

  // Convert back with new lightness
  const newL = targetL;
  const hue2rgb = (p: number, q: number, t: number) => {
    if (t < 0) t += 1;
    if (t > 1) t -= 1;
    if (t < 1 / 6) return p + (q - p) * 6 * t;
    if (t < 1 / 2) return q;
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
    return p;
  };

  let nr: number, ng: number, nb: number;
  if (s === 0) {
    nr = ng = nb = newL;
  } else {
    const q = newL < 0.5 ? newL * (1 + s) : newL + s - newL * s;
    const p = 2 * newL - q;
    nr = hue2rgb(p, q, h + 1 / 3);
    ng = hue2rgb(p, q, h);
    nb = hue2rgb(p, q, h - 1 / 3);
  }

  const toHex = (v: number) =>
    Math.round(Math.max(0, Math.min(1, v)) * 255)
      .toString(16)
      .padStart(2, "0");
  return `#${toHex(nr)}${toHex(ng)}${toHex(nb)}`;
}

// --- Format names to file names ---

const FORMAT_FILES: Record<string, string> = {
  css: "tokens.css",
  scss: "tokens.scss",
  tailwind: "tailwind.devsigner.js",
  json: "tokens.json",
  figma_tokens: "figma-tokens.json",
};

type TokenFormat = "css" | "scss" | "tailwind" | "json" | "figma_tokens";

const PERSONALITY_NAMES = PERSONALITIES.map((p) => p.name) as [string, ...string[]];

export function registerExportTokens(server: McpServer): void {
  server.tool(
    "export_tokens",
    "Export design identity tokens in multiple formats (CSS variables, Tailwind config, SCSS, W3C JSON, Figma Tokens). Reads from a project's .devsigner/context.json or generates tokens from a personality archetype.",
    {
      project_path: z
        .string()
        .optional()
        .describe("Path to project root — reads identity from .devsigner/context.json"),
      personality: z
        .enum(PERSONALITY_NAMES)
        .optional()
        .describe(
          "Generate tokens from a personality archetype if no project_path is provided"
        ),
      formats: z
        .array(z.enum(["css", "tailwind", "scss", "json", "figma_tokens"]))
        .default(["css", "tailwind", "json"])
        .describe("Output formats to generate"),
      output_dir: z
        .string()
        .optional()
        .describe("If provided, write token files to this directory on disk"),
    },
    async ({ project_path, personality, formats, output_dir }) => {
      // Resolve token set
      let tokens: TokenSet;
      let sourceName: string;

      if (project_path) {
        const ctx = await loadContext(project_path);
        if (!ctx.identity) {
          return {
            content: [
              {
                type: "text" as const,
                text: `No design identity found in ${project_path}/.devsigner/context.json. Run design_identity first to create one, or pass a \`personality\` parameter.`,
              },
            ],
            isError: true,
          };
        }
        tokens = identityToTokenSet(ctx.identity);
        sourceName = ctx.identity.personality;
      } else if (personality) {
        try {
          tokens = personalityToTokenSet(personality);
          sourceName = personality;
        } catch (err) {
          return {
            content: [
              {
                type: "text" as const,
                text: err instanceof Error ? err.message : String(err),
              },
            ],
            isError: true,
          };
        }
      } else {
        return {
          content: [
            {
              type: "text" as const,
              text: "Provide either `project_path` (to read from .devsigner/context.json) or `personality` (to generate from an archetype).",
            },
          ],
          isError: true,
        };
      }

      // Generate requested formats
      const results: Record<string, string> = {};
      for (const fmt of formats as TokenFormat[]) {
        switch (fmt) {
          case "css":
            results.css = generateCSS(tokens);
            break;
          case "scss":
            results.scss = generateSCSS(tokens);
            break;
          case "tailwind":
            results.tailwind = generateTailwind(tokens);
            break;
          case "json":
            results.json = generateJSON(tokens);
            break;
          case "figma_tokens":
            results.figma_tokens = generateFigmaTokens(tokens);
            break;
        }
      }

      // Write files if output_dir provided
      const writtenFiles: string[] = [];
      if (output_dir) {
        await mkdir(output_dir, { recursive: true });
        for (const fmt of formats as TokenFormat[]) {
          const fileName = FORMAT_FILES[fmt];
          const filePath = join(output_dir, fileName);
          await writeFile(filePath, results[fmt], "utf-8");
          writtenFiles.push(filePath);
        }
      }

      // Build output
      const sections: string[] = [
        `# Design Tokens: ${sourceName}`,
        "",
      ];

      if (writtenFiles.length > 0) {
        sections.push("## Files Written");
        for (const f of writtenFiles) {
          sections.push(`- \`${f}\``);
        }
        sections.push("");
      }

      for (const fmt of formats as TokenFormat[]) {
        const fileName = FORMAT_FILES[fmt];
        const lang =
          fmt === "css"
            ? "css"
            : fmt === "scss"
              ? "scss"
              : fmt === "tailwind"
                ? "js"
                : "json";
        sections.push(`## ${fileName}`);
        sections.push("");
        sections.push("```" + lang);
        sections.push(results[fmt]);
        sections.push("```");
        sections.push("");
      }

      return {
        content: [{ type: "text" as const, text: sections.join("\n") }],
      };
    }
  );
}
